/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ChatEvents {
  event_type: string;
  id: Generated<Int8>;
  job_id: string;
  payload_json: Json;
  received_at: Generated<Timestamp>;
  seq: number;
  session_id: string;
}

export interface ChatMessages {
  content: Generated<string>;
  content_raw: string | null;
  created_at: Generated<Timestamp>;
  error_code: string | null;
  error_message: string | null;
  id: Generated<string>;
  job_id: string | null;
  message_index: number;
  mode: Generated<string>;
  role: string;
  session_id: string;
  sources_json: Json | null;
  status: Generated<string>;
  trace_id: string | null;
  turn: Generated<number>;
  usage_completion: number | null;
  usage_prompt: number | null;
}

export interface ChatSessions {
  created_at: Generated<Timestamp>;
  delete_requested_at: Timestamp | null;
  id: Generated<string>;
  status: Generated<string>;
  title: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Departments {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  name: string;
}

export interface FileAccessLog {
  accessed_at: Generated<Timestamp | null>;
  action: string | null;
  file_id: string;
  id: Generated<Int8>;
  ip_address: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface FileChunks {
  /**
   * Stable order of the chunk within the file.
   */
  chunk_index: number;
  created_at: Generated<Timestamp | null>;
  /**
   * FK → file_metadata.id (the file this chunk belongs to).
   */
  file_id: string;
  id: string;
  /**
   * JSONB metadata: section_title, section_level, offsets, block_id, page, etc.
   */
  meta: Generated<Json | null>;
  /**
   * Chunk text used for embedding / search.
   */
  text: string;
}

export interface FileJobs {
  error_message: string | null;
  file_id: string;
  finished_at: Timestamp | null;
  id: Generated<string>;
  job_type: string;
  started_at: Timestamp | null;
  status: Generated<string>;
}

export interface FileMetadata {
  bucket: string;
  checksum: string | null;
  chunk_count: number | null;
  content_type: string | null;
  created_at: Generated<Timestamp | null>;
  delete_requested_at: Timestamp | null;
  deleted_at: Timestamp | null;
  department_id: string | null;
  embedding_model: string | null;
  etag: string | null;
  filename: string;
  id: Generated<string>;
  indexed_at: Timestamp | null;
  key: string;
  language: string | null;
  meta: Generated<Json | null>;
  modified_at: Timestamp | null;
  owner_id: string;
  size: Int8 | null;
  source_url: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp | null>;
  uploaded_at: Timestamp | null;
  vectorized_at: Timestamp | null;
  vectors_deleted_at: Timestamp | null;
  visibility: Generated<string | null>;
}

export interface JobEvents {
  created_at: Generated<Timestamp>;
  /**
   * Event name, e.g., rag_retrieve.in_progress.
   */
  event: string;
  id: Generated<string>;
  /**
   * Job UUID (correlates with chat jobs).
   */
  job_id: string;
  /**
   * Event payload JSON (query, hits, tookMs, etc).
   */
  payload: Json | null;
  /**
   * Optional session UUID for chat jobs.
   */
  session_id: string | null;
  /**
   * Owner user UUID.
   */
  user_id: string;
}

export interface Jobs {
  created_at: Generated<Timestamp>;
  error: string | null;
  id: Generated<string>;
  session_id: string;
  status: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface LlmMetrics {
  /**
   * Token count of generated completion.
   */
  completion_tokens: Generated<number>;
  count_eot: Generated<boolean>;
  /**
   * Insertion timestamp.
   */
  created_at: Generated<Timestamp>;
  /**
   * Error text for failed requests (truncated if too long).
   */
  error_message: string | null;
  /**
   * Generation duration (first to last token).
   */
  gen_time_ms: number | null;
  id: Generated<Int8>;
  /**
   * Model display name (e.g., gpt-4o-mini, llama3-8b).
   */
  model_name: string;
  /**
   * Physical or relative model path (e.g., gguf filename).
   */
  model_path: Generated<string>;
  notes: string | null;
  /**
   * Character count of generated output.
   */
  output_chars: Generated<number>;
  /**
   * Parent span for hierarchical trace linking.
   */
  parent_span_id: string | null;
  /**
   * Character count of prompt (input text).
   */
  prompt_chars: Generated<number>;
  /**
   * Token count of prompt (input tokens).
   */
  prompt_tokens: Generated<number>;
  /**
   * LLM provider or runtime backend (e.g., openai, vllm, unknown).
   */
  provider: Generated<string>;
  /**
   * Latency from outbox published_at to first token (DB clock).
   */
  published_to_first_token_ms: number | null;
  /**
   * Outbox queue delay (created_at -> published_at) in milliseconds.
   */
  queue_ms: number | null;
  /**
   * Number of retrieved documents used in RAG context.
   */
  rag_hits: Generated<number>;
  /**
   * RAG preprocessing duration (retrieval + compression + prompt build) in milliseconds.
   */
  rag_ms: number | null;
  /**
   * External request UUID, used for cross-system correlation.
   */
  request_id: string;
  /**
   * Semantic tag for job type (e.g., llm:chat, llm:ingest).
   */
  request_tag: string | null;
  /**
   * Response code (0=OK, 1=TIMEOUT, 2=ERROR, etc.).
   */
  response_status: Generated<number | null>;
  schema_version: Generated<number>;
  /**
   * Child span ID (unique per LLM invocation).
   */
  span_id: string;
  /**
   * Human-readable span name (e.g., text, tool, rag).
   */
  span_name: string | null;
  /**
   * Throughput: total_tokens / total_ms * 1000.
   */
  tok_per_sec: number | null;
  /**
   * End-to-end total latency (queue_ms + rag_ms + worker LLM) in milliseconds.
   */
  total_ms: number | null;
  /**
   * Computed total = prompt_tokens + completion_tokens.
   */
  total_tokens: Generated<number | null>;
  /**
   * Root trace ID for distributed tracing (OpenTelemetry style).
   */
  trace_id: string;
  /**
   * Time-to-first-token in milliseconds.
   */
  ttft_ms: number | null;
  /**
   * Indicates if the request used retrieval-augmented generation.
   */
  use_rag: Generated<boolean>;
  /**
   * User owning this request (optional for system jobs).
   */
  user_id: string | null;
}

export interface LlmMetricsCompact {
  completion_tokens: number | null;
  count_eot: boolean | null;
  created_at: Timestamp | null;
  gen_time_ms: number | null;
  id: Int8 | null;
  model_name: string | null;
  model_path: string | null;
  output_chars: number | null;
  parent_span_id: string | null;
  prompt_chars: number | null;
  prompt_tokens: number | null;
  provider: string | null;
  rag_hits: number | null;
  request_id: string | null;
  request_tag: string | null;
  schema_version: number | null;
  span_id: string | null;
  span_name: string | null;
  tok_per_sec: number | null;
  total_ms: number | null;
  trace_id: string | null;
  ttft_ms: number | null;
  use_rag: boolean | null;
  user_id: string | null;
  v_total_tokens: number | null;
}

export interface MessageCitations {
  /**
   * Stable chunk identifier from retrieval index.
   */
  chunk_id: string;
  created_at: Generated<Timestamp>;
  file_name: string;
  file_uri: string | null;
  id: Generated<string>;
  /**
   * FK to chat_messages.id (assistant final message).
   */
  message_id: string;
  page: number | null;
  /**
   * LLM reranker score if available.
   */
  rerank_score: number | null;
  /**
   * FK to chat_sessions.id (redundant for query speed / filtering).
   */
  session_id: string;
  snippet: string | null;
  /**
   * Local citation id (e.g., S1, S2) used in the answer text.
   */
  source_id: string;
}

export interface Outbox {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  idempotency_key: string | null;
  job_id: string | null;
  key: string | null;
  last_attempt_at: Timestamp | null;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  note: string | null;
  payload_json: Json;
  published_at: Timestamp | null;
  retry_count: Generated<number>;
  status: Generated<string>;
  topic: string;
}

export interface ToolingPromptRuns {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<Int8>;
  input_vars: Json | null;
  latency_ms: number | null;
  model: string | null;
  prompt_version_id: Int8 | null;
}

export interface ToolingPrompts {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  is_archived: Generated<boolean>;
  latest_version: number | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface ToolingPromptTags {
  prompt_id: string;
  tag_id: Int8;
}

export interface ToolingPromptVersions {
  content: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<Int8>;
  metadata: Json | null;
  prompt_id: string;
  variables: Json | null;
  version: number;
}

export interface ToolingTags {
  id: Generated<Int8>;
  name: string;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  email: string | null;
  id: Generated<string>;
  last_accessed_at: Timestamp | null;
  public_ns: Generated<string>;
  pwd_shadow: string | null;
  pwd_updated_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface DB {
  chat_events: ChatEvents;
  chat_messages: ChatMessages;
  chat_sessions: ChatSessions;
  departments: Departments;
  file_access_log: FileAccessLog;
  file_chunks: FileChunks;
  file_jobs: FileJobs;
  file_metadata: FileMetadata;
  job_events: JobEvents;
  jobs: Jobs;
  llm_metrics: LlmMetrics;
  llm_metrics_compact: LlmMetricsCompact;
  message_citations: MessageCitations;
  outbox: Outbox;
  "tooling.prompt_runs": ToolingPromptRuns;
  "tooling.prompt_tags": ToolingPromptTags;
  "tooling.prompt_versions": ToolingPromptVersions;
  "tooling.prompts": ToolingPrompts;
  "tooling.tags": ToolingTags;
  users: Users;
}
